update: do not capture during night
NaiveNeuron/PKSpace pull request #1
Opened 2016-10-21 22:22 UTC by Adman

Signed-off-by: Adrian Matejov <a.matejov@centrum.sk>

2016-10-21 22:25 UTC, Adman commented
@mrshu @Foxiy Please let me know whether this is a good way of detecting the bright/dark images. I'm kinda newbie to this opencv stuff and will appreciate any good advices.

2016-10-22 17:56 UTC, mrshu commented
@Adman Nice first pass. I think it needs a bit more thought though. Let's sync up on it with @Foxiy in the next few days.

2016-10-22 17:57 UTC, mrshu commented on scripts/capture.py
> +for i in range(15):
@Adman the `15` in here needs to be somehow configurable.

2016-10-22 17:57 UTC, mrshu commented on scripts/capture.py
> +if nonzero - nonzero_inv > 0:
@Foxiy what is your view on this? I am not convinced this is the best approach and believe that we should discuss it further.

2016-10-22 18:23 UTC, vidriduch requested changes

2016-10-22 18:23 UTC, Foxiy commented on scripts/capture.py
> +for i in range(15):
I would strongly recommend to add or configuration file or (and this is my preferred option) a way tto set it from cli maybe something like `--warmup 15` or `-w 15`

2016-10-22 18:23 UTC, Foxiy commented on scripts/capture.py
> +if nonzero - nonzero_inv > 0:
Well I think we definitely shouldn't do two thresholds. We are effectively asking here how many pixels there are that have lower intensity value that 80 from all the pixels. So same effect can be probably achieved by just comparing it to 1/3 of total number of pixels or by replacing the second threshold with numpy operation something like `np.count_nonzero(grayimg < 80)`. Or you can just simply ask what is the highest intensity pixel with max and if it is less then lets say 20 then everything else is lower therefore even blacker.

2016-10-22 18:23 UTC, Foxiy commented on scripts/capture.py
> +ret, frame = cap.read()
@Adman you should always check the return value. It will save you from lot of headaches.

2016-10-29 12:24 UTC, Adman commented
@mrshu @Foxiy warmup is now configurable. Also, I got rid of 2 thresholds and now the image is being saved only when there is less than 1/3 of dark pixels.

2016-10-29 13:53 UTC, mrshu requested changes
@Adman Looks pretty nice, just couple of suggestions.

2016-10-29 13:53 UTC, mrshu commented on scripts/capture.py
> +    for i in range(15):
@Adman there is `warmup` now, it seems that it should be used rather than a hardcoded `15`.

2016-10-29 13:53 UTC, mrshu commented on scripts/capture.py
> +    _, thresh = cv2.threshold(grayimg, 60, 255, cv2.THRESH_BINARY)
@Adman It seems a comment here (especially on the `60`) would be in order.

2016-10-29 14:45 UTC, mrshu commented
@Adman looks good and ready for merge from my point of view.

My only concern is that I never saw `requirements.pip` -- it seems that `requirements.txt` is much more common.

2016-10-29 20:47 UTC, mrshu approved these changes

2016-10-29 20:54 UTC, Foxiy commented
@Adman :+1:  LGTM. Thanks for making corrections, nicely done. Lets get it merged.

2016-10-29 20:55 UTC, vidriduch approved these changes

2016-10-29 20:59 UTC, merged